version: "3"

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: users-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  hash-translator:
    build:
      context: hashtranslator-service
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      SPRING_DATA_MONGODB_DATABASE: hash-db
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: root
      # Credentials for md5decrypt.net
      3RD_PARTY_EMAIL:
      3RD_PARTY_CODE:
      # API for auth
      AUTH_SERVICE_URL: http://authorization-service:8081/auth
    ports:
      - "8080:8080"

  authorization-service:
    build:
      context: authorization-service
    depends_on:
      - postgres
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Please add email and password for default admin
      APP_ADMIN_EMAIL:
      APP_ADMIN_PASSWORD:
    ports:
      - "8081:8081"

volumes:
  postgres-data:
  mongodb-data: